openapi: 3.0.0
info:
  title: Your API Title
  description: Description of your API
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production server (replace with your actual production URL)
  - url: https://staging.api.example.com/v1
    description: Staging server (replace with your actual staging URL)
paths:
  /api/endpoint:
    get:
      summary: Endpoint summary
      description: Detailed description of what this endpoint does.
      responses:
        '200':
          description: A successful response
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Internal server error
    post:
      summary: Create a resource
      description: Endpoint to create a new resource.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                property1:
                  type: string
                property2:
                  type: integer
      responses:
        '201':
          description: Resource created successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
